# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: bluszcz.net
subtitle: "Open Source, art and bit of everything"
email: bluszcz@bluszcz.net
description: >- # this means to ignore newlines until "baseurl:"
  This is my technical / creative blog where I will be sharing updates
  about my Open Source, Tech or Multimedia related work. Have a fun!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bluszcz.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  bluszcz
markdown: kramdown
# Build settings
# remote_theme: bluszcz/jekyll-theme-devcarpet-01
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  # - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

devcarpet_theme:
  social_links:
    github:  bluszcz
    vimeo: devcarpet
    youtube_channel: UCH8bTGji7CZzSExtFGzvdMQ
    youtube_channel_name: DevCarpet
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# social:
#   type:  # Person or Organization (defaults to Person)
#   name:  # If the user or organization name differs from the site's name
#   links:
#     - "https://instagram.com/betaidoru666"
#     - "https://mastodon.art/@bluszcz"
#     - "https://youtube.com/@devcarpet""

author:
  name     : "bluszcz"
  bio      : "Open Source nerd. Fan of Python. DevOps for life. Linux user. Captures world with the help of Black Magic Cinema Pocket Camera 4K."
  location : "Barcelona, Spain"
  uri      : "https://mastodon.art/@bluszcz"
  links:
    - label: "Github"
      icon: "fas fa-fw fa-github"
      url: "https://github.com/bluszcz"


collections:
  projects:
    output: true
    permalink: /:collection/:path/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _portfolio
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true
include: ["_pages"]
lunr:
  search_within_pages: true
search: true
og_image: /assets/images/Banner-Bluszcz.png